# Generated by Django 4.1.5 on 2023-01-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categoryadmin_productadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productadmin',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='CategoryAdmin',
        ),
        migrations.DeleteModel(
            name='ProductAdmin',
        ),
    ]
